### ISSUE TITLE
Error on install generator in solidus 2.10.2

### ISSUE THREAD

**Issue by hamiljs** [solidusio-contrib/solidus_asset_variant_options#44]
While trying to run the install generator I see the error message

```ruby
vagrant@ubuntu-bionic:/vagrant$ bundle exec rails g solidus_asset_variant_options:install
set_default_options has been deprecated, use set_options
/home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/solidus_core-2.10.2/lib/spree/preferences/preferable.rb:162: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
/home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/friendly_id-5.3.0/lib/friendly_id/history.rb:75: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/associations.rb:1370: warning: The called method `has_many' is defined here
/home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/solidus_asset_variant_options-1.0.2/app/helpers/spree/admin/images_helper_decorator.rb:1:in `<main>': uninitialized constant Spree::Admin::ImagesHelper
Did you mean?  Spree::Admin::BaseHelper (NameError)
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/solidus_asset_variant_options-1.0.2/lib/spree_asset_variant_options/engine.rb:16:in `block in activate'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/solidus_asset_variant_options-1.0.2/lib/spree_asset_variant_options/engine.rb:15:in `glob'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/solidus_asset_variant_options-1.0.2/lib/spree_asset_variant_options/engine.rb:15:in `activate'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:428:in `instance_exec'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:428:in `block in make_lambda'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:604:in `catch'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:604:in `block in default_terminator'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:201:in `block in halting'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:513:in `each'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:513:in `invoke_before'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:134:in `run_callbacks'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:88:in `prepare!'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/application/finisher.rb:113:in `block in <module:Finisher>'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `run'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `each'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `call'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/application.rb:363:in `initialize!'
        from /vagrant/config/environment.rb:6:in `<main>'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
vagrant@ubuntu-bionic:/vagrant$         from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:106:in `preload'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /home/vagrant/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from -e:1:in `<main>'
```

Current Gemfile includes

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'dotenv-rails', require: 'dotenv/rails-now'
gem 'solidus'
gem 'solidus_auth_devise'
gem 'slim-rails'
gem 'solidus_sitemap', github: 'solidusio-contrib/solidus_sitemap'
# gem 'solidus_simple_dash', github: 'magma-labs/solidus_simple_dash'
# gem 'solidus_reports', github: 'solidusio-contrib/solidus_reports'

gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
gem 'pg'
gem "passenger"
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 4.0'
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
gem 'google-analytics-rails'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'whenever', require: false
gem 'streamio-ffmpeg'
gem 'rmagick'
gem 'geokit'
gem "solidus_asset_variant_options"
```

**Comment by pacarvalho** [comment]
@hamiljs Did you figure out how to solve this?

**Comment by hamiljs** [comment]
No. I just didn't use this as my solution because of the failure. I may come back to it, but it was still an issue the last time I checked.

**Comment by hamiljs** [comment]
To me it looks like a require is missing for Spree::Admin::ImageHelper in solidus_asset_variant_options-1.0.2/app/helpers/spree/admin/images_helper_decorator.rb
I can't find the origin of that file to add a require.  Actually, I also can't find Spree::Admin::ImageHelper either.

**Comment by hamiljs** [comment]
The issue is the gem at rubygems. If I pull from github, all is well.
